apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  MONGO_URL: "mongodb://mongodb:27017"
  PRODUCT_SERVICE_URL: "http://product-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
