apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: ecommerce-services
    app.kubernetes.io/part-of: ecommerce-root-app
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/devops-project-2026.git
    targetRevision: HEAD
    path: k8s/deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
